/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Tools.Tools;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Abdelatif Hamdi
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMyBottom1 = new controls.JMyBottom();
        jMyBottom2 = new controls.JMyBottom();
        jMyBottom3 = new controls.JMyBottom();
        btnExit1 = new controls.JMyBottom();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Accueil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 70, 266, 49);

        jMyBottom1.setText("Etudiant");
        jMyBottom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMyBottom1MouseClicked(evt);
            }
        });
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMyBottom1);
        jMyBottom1.setBounds(140, 150, 146, 32);

        jMyBottom2.setText("Enseignant");
        jMyBottom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom2ActionPerformed(evt);
            }
        });
        getContentPane().add(jMyBottom2);
        jMyBottom2.setBounds(140, 220, 146, 32);

        jMyBottom3.setText("Employée");
        jMyBottom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom3ActionPerformed(evt);
            }
        });
        getContentPane().add(jMyBottom3);
        jMyBottom3.setBounds(140, 290, 146, 32);

        btnExit1.setText("Sortir");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit1);
        btnExit1.setBounds(60, 380, 83, 23);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try { 
            Image img2 = ImageIO.read(Tools.class.getResource("ecolePhoto.jpg"));
            Image newi = img2.getScaledInstance(422, 447, Image.SCALE_AREA_AVERAGING);
      ImageIcon az = new ImageIcon(newi);  
      jLabel2.setIcon(az);
        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_formWindowOpened

    private void jMyBottom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom3ActionPerformed
//this.dispose();
        Tools.OpenForm(new frmEmployée());    }//GEN-LAST:event_jMyBottom3ActionPerformed

    private void jMyBottom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMyBottom1MouseClicked

    }//GEN-LAST:event_jMyBottom1MouseClicked

    private void jMyBottom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom2ActionPerformed
        //this.dispose();
        Tools.OpenForm(new frmEnseignant());
    }//GEN-LAST:event_jMyBottom2ActionPerformed

    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
//this.dispose();
        Tools.OpenForm(new frmEtudiant());    }//GEN-LAST:event_jMyBottom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBottom btnExit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private controls.JMyBottom jMyBottom1;
    private controls.JMyBottom jMyBottom2;
    private controls.JMyBottom jMyBottom3;
    // End of variables declaration//GEN-END:variables
}
